In [1]:
!curl -LsSf https://astral.sh/uv/install.sh | sh

downloading uv 0.11.2 x86_64-unknown-linux-gnu
installing to /root/.local/bin
  uv
  uvx
everything's installed!

In [2]:
!uv self update

info: Checking for updates...

success: You're already on version v0.11.2 of uv (the latest version).

# Creating virtual enviroment
    1  uv venv mienv
    2  uv pip install ipykernel
    3  python -m ipykernel install --user --name=mienv

In [3]:
    # uv venv mienv
    # uv pip install ipykernel --python ./mienv/bin/python
    # ./mienv/bin/python -m ipykernel install --user --name=mienv --display-name "Python (mienv-Jose)"
    # history

In [1]:
!uv pip install numpy
!uv pip install pandas

Using Python 3.12.13 environment at: mienv
Resolved 1 package in 95ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.

Installed 1 package in 620ms
 + numpy==2.4.4
Using Python 3.12.13 environment at: mienv
Resolved 4 packages in 116ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 746ms
 + pandas==3.0.2

In [2]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
date = pd.date_range("20260102",periods=6)
date

DatetimeIndex(['2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05',
               '2026-01-06', '2026-01-07'],
              dtype='datetime64[us]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6,4), index=date, columns=list("ABCD"))
df

                   A         B         C         D
2026-01-02 -0.622852  0.341767 -0.569208 -0.779990
2026-01-03  1.388171 -1.009390 -0.577706 -1.467306
2026-01-04  1.430501  1.010983  0.285780  0.039386
2026-01-05  0.492954  0.905361  2.434550 -0.100224
2026-01-06 -0.783960  1.733609  0.393647  0.354749
2026-01-07 -0.834127  2.281891 -0.804407 -1.810540

In [12]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20260326"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3]*4,dtype="int32"),
        "E": pd.Categorical(["test","train","test","train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2026-03-26  1.0  3   test  foo
1  1.0 2026-03-26  1.0  3  train  foo
2  1.0 2026-03-26  1.0  3   test  foo
3  1.0 2026-03-26  1.0  3  train  foo

In [13]:
df.head()

                   A         B         C         D
2026-01-02 -0.020359  0.215364  0.636051  0.678763
2026-01-03  0.558594 -1.539993 -0.375079  0.178057
2026-01-04 -1.021045  0.738316  0.039057  0.060831
2026-01-05 -0.236141 -3.021831  1.140471  1.017491
2026-01-06  1.605811 -0.773355  0.361764 -0.238032

In [14]:
df.tail(3)

                   A         B         C         D
2026-01-05 -0.236141 -3.021831  1.140471  1.017491
2026-01-06  1.605811 -0.773355  0.361764 -0.238032
2026-01-07  0.244171  0.568194  1.590172 -1.340688